model:
  channels: 3
  num_classes: 1
  backbone_name: 'resnet50'
  pretrained: true
  freeze_grad: false
  kernel_size: 3
  bias: false
  normalize: null
  dropout: 0.0
  init_weights: true

  ensemble:
    null
    # channels: 3
    # num_classes: 1
    # backbone_name: 'resnet50'
    # pretrained: true
    # freeze_grad: false
    # kernel_size: 3
    # bias: false
    # normalize: null
    # dropout: 0.0
    # init_weights: true

augmentation:
  channels: 3
  resize: [320, 320]
  hflip: true
  vflip: true
  rotate: 45
  saturation: 0.5
  brightness: 0.5
  factor: 1
  p: 0.5

dataloader:
  image_path: 'dataset/image'
  mask_path: 'dataset/mask'
  extension: '.jpg'
  num_images: 0

dataset:
  dataset_split: {'train': 0.85, 'val': 0.1}
  batch_size: 8
  shuffle: true
  num_workers: 8
  pin_memory: true

trainer:
  train: true
  lr: 0.0005
  epochs: 100
  accumulation_step: 4
  checkpoint_step: 20
  show_time: 0.5
  csv_path: 'csv/'
  csv_name: 'train_logg.csv'
  checkpoint_path: 'model/checkpoint'
  model_path: 'model'

tester:
  test: true
  threshold: 0.8
  model_path: 'model/model.pth'
  image_path: 'dataset/test/test.jpg'

